#HELLO

In [1]:
import numpy as np

In [2]:
#creating a 1d array and also definying its memory

a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [3]:
#getting dinmesions
a.ndim


1

In [4]:
#getting shape
a.shape


(3,)

In [5]:
#getting data type
a.dtype

dtype('int32')

In [6]:
#get total size
a.nbytes

12

In [7]:
#creating a 2d array
b=np.array([[1,2,3,4,5,6,7],[5,6,4,9,4,5,5]])
print(b)

[[1 2 3 4 5 6 7]
 [5 6 4 9 4 5 5]]


In [8]:
#creating a transpose
b.T

array([[1, 5],
       [2, 6],
       [3, 4],
       [4, 9],
       [5, 4],
       [6, 5],
       [7, 5]])

In [9]:
#getting specific element from an array
b[1,3]

9

In [10]:
#getting a specific row
b[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
#getting a specific column
b[:,2]

array([3, 4])

In [12]:
#getting equally spaced elements
lspace=np.linspace(1,50,13)
lspace

array([ 1.        ,  5.08333333,  9.16666667, 13.25      , 17.33333333,
       21.41666667, 25.5       , 29.58333333, 33.66666667, 37.75      ,
       41.83333333, 45.91666667, 50.        ])

In [13]:
#changing elements
b[1,1]=15
print(b)
b[:,2]=[77,83]
print(b)

[[ 1  2  3  4  5  6  7]
 [ 5 15  4  9  4  5  5]]
[[ 1  2 77  4  5  6  7]
 [ 5 15 83  9  4  5  5]]


In [14]:
#3d example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
#getting a specific elemenet in an 3d array
b[0,1,1]
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [16]:
#replace 
b[:,1,:]=[54,32]
print(b)

[[[ 1  2]
  [54 32]]

 [[ 5  6]
  [54 32]]]


In [17]:
#all zero matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.ones((4,2,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [19]:
#any other array
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [20]:
#any other number(full_like)
np.full_like(a,7)


array([7, 7, 7])

In [21]:
#any other number(.shape)
np.full(a.shape,8)

array([8, 8, 8])

In [22]:
#random decimal number array
np.random.rand(4,2)

array([[0.66148758, 0.02885924],
       [0.31097177, 0.47325559],
       [0.91958237, 0.80197122],
       [0.63679169, 0.98025218]])

In [23]:
#random decimal number of known shape
np.random.random_sample(a.shape)

array([0.11823034, 0.82010574, 0.52544144])

In [24]:
#random integer values
np.random.randint(7,size=(3,3))

array([[1, 3, 1],
       [0, 0, 0],
       [1, 2, 3]])

In [25]:
#repeating an array
arr=np.array([{1,2,3}])
r1=np.repeat(arr,3,axis=0)
print(r1)


[{1, 2, 3} {1, 2, 3} {1, 2, 3}]


In [26]:
arr1=np.ones((5,5))
print(arr1)
arr2=np.zeros((3,3))
arr2[1,1]=9
print(arr2)
arr1[1:4,1:4]=arr2
print(arr1)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
#making a copy of an array
a=np.array([1,2,3])
b=a.copy()
b[0]=45
print(a)
print(b)

[1 2 3]
[45  2  3]


#####mathematics


In [28]:
c=np.array([1,2,3,4,5])
print(c )

[1 2 3 4 5]


In [29]:
c/2


array([0.5, 1. , 1.5, 2. , 2.5])

In [30]:
c*2

array([ 2,  4,  6,  8, 10])

In [31]:
c-2

array([-1,  0,  1,  2,  3])

In [32]:
c*2

array([ 2,  4,  6,  8, 10])

In [33]:
d=np.array([6,7,8,9,10])
print(d)

[ 6  7  8  9 10]


In [34]:
c/d

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [35]:
c**2

array([ 1,  4,  9, 16, 25])

In [36]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

###linear algebra

In [37]:
#multiplying two matrix
a= np.ones((2,3))
print(a)
b=np.full((3,2),4)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]


In [38]:
np.matmul(a,b)

array([[12., 12.],
       [12., 12.]])

In [39]:
#finding the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [40]:
###statistics


In [41]:
 stats=np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [42]:
#finding min(max)
np.min(stats,axis=0)

array([1, 2, 3])

In [43]:
np.min(stats,axis=1)

array([1, 4])

In [44]:
np.min(stats)

1

In [45]:
#adding arrays
np.sum(stats)

21

In [46]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [47]:
##reorganizing arrays

In [48]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
##verticle stacking
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
#horizontal stacking
h1=np.zeros((2,4))
h2=np.ones((2,2))
np.hstack((h1,h2))

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

#miscellaneous



In [51]:
#load data from file 
filedata=np.genfromtxt('New Text Document.txt',delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[   2    1   45    5    5    6    9    4   21   64   66    2   45   78
   11   55 4646    2    9    8   75    8    9    6    5    5   57]


# boolean masking and advance indexing

In [52]:
 #you can index with list in numpy
a=np.array([56,87,54,42,89,65,47])
a[[1,2,5]]

array([87, 54, 65])

In [53]:
filedata>50

array([False, False, False, False, False, False, False, False, False,
        True,  True, False, False,  True, False,  True,  True, False,
       False, False,  True, False, False, False, False, False,  True])

In [54]:
filedata[filedata>50]

array([  64,   66,   78,   55, 4646,   75,   57])

In [55]:
np.any(filedata>50,axis=0)

True

In [56]:
np.all(filedata>50,axis=0)

False

In [57]:
((filedata>50)&(filedata<100))

array([False, False, False, False, False, False, False, False, False,
        True,  True, False, False,  True, False,  True, False, False,
       False, False,  True, False, False, False, False, False,  True])